#!/usr/bin/env python

import sys


def is_stdlib(module: str) -> bool:
    """
    Return True if module is in stdlib
    """

    return module.split(".")[0] in sys.stdlib_module_names


def main():
    for line in sys.stdin.readlines():
        line = line.removeprefix("import").strip()
        print(f"{line}: {is_stdlib(line)}")
    return


if __name__ == "__main__":
    main()
